# Generated by Django 3.2.19 on 2023-06-21 06:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='slug',
            field=models.SlugField(default=1, max_length=155, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comments',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_comments', to='loans.books'),
        ),
        migrations.AlterField(
            model_name='loans',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_loans', to='loans.books'),
        ),
        migrations.AlterField(
            model_name='loans',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_loans', to=settings.AUTH_USER_MODEL),
        ),
    ]
