# Generated by Django 3.2.19 on 2023-06-22 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lendingtest',
        ),
    ]
