# Generated by Django 3.2.19 on 2023-06-22 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_delete_lendingtest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loan',
            options={'managed': True, 'ordering': ['created_on']},
        ),
    ]
