# Generated by Django 3.2.19 on 2023-06-23 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0003_alter_loan_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loan',
            options={'ordering': ['created_on']},
        ),
    ]
