# Generated by Django 3.2.19 on 2023-06-21 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0004_auto_20230621_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='pub_year',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
