# Generated by Django 3.2.19 on 2023-06-27 14:31

from django.db import migrations, models
import loans.models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0005_auto_20230623_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='expire',
            field=models.DateTimeField(blank=True, default=loans.models.add_one_week_at_today),
        ),
        migrations.AlterField(
            model_name='loan',
            name='number_renowals',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='loan',
            name='status',
            field=models.IntegerField(blank=True, choices=[(1, 'Reserved'), (2, 'Loaned'), (3, 'Returned'), (4, 'Canceled'), (5, 'Lost')], default=1),
        ),
    ]
